In [1]:
import pandas as pd
from suppliers_map import supplier_files_dict
import sqlite3
import os
import holidays
import datetime

from main import export_files_directory_path, mb51_consumption_dtypes, MB51_new_col_names
from helper_functions import extract_unique_mb51_files, load_grouped_mb51_dataframes, consolidate_and_save_data, update_sap_database, get_past_workdays

### Save data to DB

In [2]:
# export_files_directory_path = r"\\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\05_PURCHASING_AUTOMATION\CONS_last_80_days"

# MB51_new_col_names = {
#     'Materiał': 'Material',
#     'Data księgowania': 'date',
#     'Ilość': 'quantity',
#     'Podst. jedn. miary': 'unit',
#     'Zakład': 'plant'
# }
#
# mb51_consumption_dtypes = {
#     'Materiał': 'string',
#     'Zakład': 'string',
# }

unique_mb51_files_dict = extract_unique_mb51_files(supplier_files_dict)
MB551_dfs = load_grouped_mb51_dataframes(
    grouped_files=unique_mb51_files_dict,
    base_path=export_files_directory_path,
    extension=".xlsx",
    dtypes_mb51=mb51_consumption_dtypes,
    col_names_mb51=MB51_new_col_names,
    ignore_missing=True
)

Processing CONS_246
Processing CONS_223
Processing CONS_224
Processing CONS_234
Processing CONS_228
Processing CONS_239
Processing CONS_337

In [3]:
update_sap_database(MB551_dfs, export_files_directory_path)

Database successfully updated. Data saved/merged in: \\rfmesrv5\connect\DST_SAP_Transfer\P11\PPS_LUB\05_PURCHASING_AUTOMATION\sap_consumption.db

### Load all data from DB

In [4]:
db_path = os.path.join(export_files_directory_path, 'sap_consumption.db')

# Połączenie z bazą danych
conn = sqlite3.connect(db_path)

# Odczyt całej tabeli 'consumption' do DataFrame
df = pd.read_sql("SELECT * FROM consumption", conn)
# df = pd.read_sql("SELECT * FROM consumption", conn, dtype=str)
df['date'] = pd.to_datetime(df['date'])
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')

# Zawsze warto zamknąć połączenie po zakończeniu pracy
conn.close()

print(f"Wczytano {len(df)} wierszy.")
print(df.head())

Wczytano 121183 wierszy.
  Material       date plant  quantity source_file group_key
0   106132 2026-06-16  2101    -423.0    CONS_246  CONS_246
1   106132 2026-06-17  2101    -480.0    CONS_246  CONS_246
2   106132 2026-06-18  2101    -448.0    CONS_246  CONS_246
3   106132 2026-06-19  2101    -405.0    CONS_246  CONS_246
4   106132 2026-06-22  2101    -345.0    CONS_246  CONS_246

In [5]:
df.head()

  Material       date plant  quantity source_file group_key
0   106132 2026-06-16  2101    -423.0    CONS_246  CONS_246
1   106132 2026-06-17  2101    -480.0    CONS_246  CONS_246
2   106132 2026-06-18  2101    -448.0    CONS_246  CONS_246
3   106132 2026-06-19  2101    -405.0    CONS_246  CONS_246
4   106132 2026-06-22  2101    -345.0    CONS_246  CONS_246

### Load specific data from DB

In [9]:
def get_consumption_from_database(db_dir, db_name, items_list: list, plant: str, days_list: list = None):
    """
    Retrieves consumption data from the SQLite database filtered by plant,
    an optional list of materials (items_list), and an optional list of workdays (days_list).
    """
    db_path = os.path.join(db_dir, db_name)
    conn = sqlite3.connect(db_path)

    # Base SQL query filtering by plant
    query = "SELECT * FROM consumption WHERE plant = ?"
    params = [plant]

    # Filter by items_list if provided and not empty
    if items_list:
        placeholders_items = ','.join(['?'] * len(items_list))
        query += f" AND Material IN ({placeholders_items})"
        params.extend(items_list)

    # Filter by days_list if provided and not empty
    if days_list:
        # Convert date objects to 'YYYY-MM-DD' strings for safe SQL comparison
        formatted_days = [
            d.strftime('%Y-%m-%d') if isinstance(d, (datetime.datetime, datetime.date)) else str(d)
            for d in days_list
        ]
        placeholders_days = ','.join(['?'] * len(formatted_days))
        query += f" AND date IN ({placeholders_days})"
        params.extend(formatted_days)

    # Execute query and read filtered data directly into a Pandas DataFrame
    df = pd.read_sql(query, conn, params=params)

    # Post-process data types if the DataFrame is not empty
    if not df.empty:
        if 'date' in df.columns:
            df['date'] = pd.to_datetime(df['date'])
        if 'quantity' in df.columns:
            df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce')

    # Close the database connection
    conn.close()

    return df

In [10]:
today = datetime.datetime.today().date()
current_year = datetime.date.today().year
years_list = [current_year - 1, current_year, current_year + 1]
pl_holidays = holidays.Poland(years=years_list)
past_10_days_now = get_past_workdays(today, 2, 'last', pl_holidays)

In [11]:
items = ['773633', '472710']
plant = "2101"
cons_df = get_consumption_from_database(export_files_directory_path, "sap_consumption.db", items, plant, past_10_days_now)

In [12]:
cons_df

  Material       date plant  quantity source_file group_key
0   773633 2026-10-12  2101     -11.0    CONS_246  CONS_246
1   773633 2026-10-13  2101      -6.0    CONS_246  CONS_246